import type { ProviderConfig } from "@agentrep/provider-kit";
import { paise } from "@agentrep/webmcp";

const DELIVERY = ["2026-09-12", "2026-09-19", "2026-09-26"];
const LATER = ["2026-09-19", "2026-09-26"];

const textMatch = (item: { name: string; blurb: string; tags: string[]; attributes: Record<string, string | number | boolean> }, q: string) => {
  const hay = `${item.name} ${item.blurb} ${item.tags.join(" ")} ${item.attributes.flavour}`.toLowerCase();
  return hay.includes(q.toLowerCase());
};

export const config: ProviderConfig = {
  brand: "CakeHub",
  domain: "cakehub-webmcp.vercel.app",
  slot: "cake",
  noun: "cake",
  nounPlural: "cakes",
  accent: "#8a3a5c",
  tagline: "Celebration cakes baked to order, sized by servings and delivered on the day.",
  bookVerb: "order",
  toolNames: {
    search: "search_cakes",
    details: "get_cake_details",
    availability: "check_delivery",
    price: "get_price",
    book: "order_cake",
  },
  filters: [
    {
      key: "query",
      type: "string",
      description: "Free-text search across cake name, flavour, tags and description. e.g. \"chocolate\", \"eggless\", \"Pokémon\".",
      match: (i, v) => textMatch(i, String(v)),
    },
    {
      key: "maxBudgetInPaise",
      type: "number",
      description: "Highest acceptable price in paise (₹2,000 = 200000).",
      match: (i, v) => i.priceInPaise <= Number(v),
    },
    {
      key: "guests",
      type: "number",
      description: "How many people the cake must serve. Filters out cakes that are too small.",
      match: (i, v) => Number(i.attributes.servings) >= Number(v),
    },
    {
      key: "flavour",
      type: "string",
      description: "Flavour family, e.g. chocolate, vanilla, mango, pistachio, strawberry.",
      match: (i, v) =>
        String(i.attributes.flavour).toLowerCase().includes(String(v).toLowerCase()),
    },
    {
      key: "theme",
      type: "string",
      description: "Decoration theme, e.g. \"Pokémon\", \"unicorn\". Matched against the cake's design tags.",
      match: (i, v) =>
        i.tags.some((t) => t.toLowerCase().includes(String(v).toLowerCase())),
    },
    {
      key: "eggless",
      type: "boolean",
      description: "Restrict to eggless cakes.",
      match: (i, v) => (v ? i.attributes.eggless === true : true),
    },
  ],
  items: [
    {
      id: "cake-pokemon",
      name: "Pokémon Cake",
      priceInPaise: paise(1800),
      blurb: "Yellow buttercream, chocolate ears, a red lightning piped on the side. Two days' notice, no exceptions.",
      attributes: { servings: 20, flavour: "chocolate", eggless: false, tiers: 1 },
      tags: ["pokemon", "themed", "kids", "yellow"],
      availableDates: DELIVERY,
    },
    {
      id: "cake-truffle",
      name: "Chocolate Truffle",
      priceInPaise: paise(1200),
      blurb: "Dark ganache, a name plaque, nothing else. The house chocolate.",
      attributes: { servings: 15, flavour: "chocolate", eggless: false, tiers: 1 },
      tags: ["classic", "budget", "chocolate"],
      availableDates: DELIVERY,
    },
    {
      id: "cake-rainbow",
      name: "Rainbow Layer",
      priceInPaise: paise(2400),
      blurb: "Six coloured sponges under vanilla buttercream. Looks dramatic when cut.",
      attributes: { servings: 25, flavour: "vanilla", eggless: true, tiers: 1 },
      tags: ["rainbow", "unicorn", "kids", "themed", "eggless"],
      availableDates: DELIVERY,
    },
    {
      id: "cake-vanilla",
      name: "Vanilla Cream",
      priceInPaise: paise(900),
      blurb: "Small eggless vanilla cake. Gold leaf, no fuss. The cheapest on the counter.",
      attributes: { servings: 12, flavour: "vanilla", eggless: true, tiers: 1 },
      tags: ["budget", "eggless", "classic"],
      availableDates: DELIVERY,
    },
    {
      id: "cake-photo",
      name: "Photo Print Cake",
      priceInPaise: paise(2000),
      blurb: "Edible print of a photo you send, on butterscotch sponge. Needs an extra day.",
      attributes: { servings: 20, flavour: "butterscotch", eggless: true, tiers: 1 },
      tags: ["custom", "photo", "pokemon", "eggless"],
      availableDates: LATER,
    },
    {
      id: "cake-blackforest",
      name: "Black Forest",
      priceInPaise: paise(1500),
      blurb: "Chocolate sponge, cream, kirsch cherries, shavings. The one people actually finish.",
      attributes: { servings: 18, flavour: "chocolate", eggless: false, tiers: 1 },
      tags: ["classic", "chocolate", "cherry"],
      availableDates: DELIVERY,
    },
    {
      id: "cake-redvelvet",
      name: "Red Velvet",
      priceInPaise: paise(1600),
      blurb: "Eggless red velvet, cream-cheese frosting. Soft crumb, sharp icing.",
      attributes: { servings: 16, flavour: "red velvet", eggless: true, tiers: 1 },
      tags: ["classic", "eggless"],
      availableDates: DELIVERY,
    },
    {
      id: "cake-mango",
      name: "Alphonso Mango",
      priceInPaise: paise(1400),
      blurb: "Season-style mango cream, fresh cubes on top. Eggless. Delhi's summer cake.",
      attributes: { servings: 14, flavour: "mango", eggless: true, tiers: 1 },
      tags: ["eggless", "fruit", "indian"],
      availableDates: DELIVERY,
    },
    {
      id: "cake-rasmalai",
      name: "Rasmalai Cake",
      priceInPaise: paise(1700),
      blurb: "Milk sponge, rasmalai, pistachio, saffron. The Indian celebration cake.",
      attributes: { servings: 16, flavour: "cardamom", eggless: true, tiers: 1 },
      tags: ["indian", "eggless", "festive"],
      availableDates: DELIVERY,
    },
    {
      id: "cake-unicorn",
      name: "Unicorn Cake",
      priceInPaise: paise(2200),
      blurb: "Pastel mane, gold horn, pearl sprinkles. For a seven-year-old who has opinions.",
      attributes: { servings: 20, flavour: "vanilla", eggless: true, tiers: 1 },
      tags: ["unicorn", "kids", "themed", "eggless"],
      availableDates: DELIVERY,
    },
    {
      id: "cake-pistachio",
      name: "Pistachio Rose",
      priceInPaise: paise(1900),
      blurb: "Pistachio sponge, rose cream, dried petals. Quiet, not a kids' cake.",
      attributes: { servings: 12, flavour: "pistachio", eggless: false, tiers: 1 },
      tags: ["classic", "nut"],
      availableDates: DELIVERY,
    },
    {
      id: "cake-freshfruit",
      name: "Fresh Fruit Cream",
      priceInPaise: paise(1300),
      blurb: "White cream, strawberries, kiwi, berries. Light enough for an afternoon party.",
      attributes: { servings: 20, flavour: "vanilla", eggless: true, tiers: 1 },
      tags: ["fruit", "eggless", "classic"],
      availableDates: DELIVERY,
    },
    {
      id: "cake-drip",
      name: "Chocolate Drip",
      priceInPaise: paise(1650),
      blurb: "White frosting, dark ganache drip, hazelnuts. Photographs well.",
      attributes: { servings: 18, flavour: "chocolate", eggless: false, tiers: 1 },
      tags: ["chocolate", "classic"],
      availableDates: DELIVERY,
    },
    {
      id: "cake-fondant",
      name: "Two-tier Fondant",
      priceInPaise: paise(3500),
      blurb: "Two tiers, ivory fondant, gold piping. For thirty people. Extra day's notice.",
      attributes: { servings: 30, flavour: "vanilla", eggless: false, tiers: 2 },
      tags: ["wedding", "fondant", "tiered"],
      availableDates: LATER,
    },
    {
      id: "cake-cookies",
      name: "Cookies & Cream",
      priceInPaise: paise(1100),
      blurb: "Crushed cookie crumb in the cream. Budget, and children finish the plate.",
      attributes: { servings: 14, flavour: "cookies and cream", eggless: false, tiers: 1 },
      tags: ["budget", "kids", "chocolate"],
      availableDates: DELIVERY,
    },
    {
      id: "cake-strawberry",
      name: "Strawberry Shortcake",
      priceInPaise: paise(1450),
      blurb: "Sponge, cream, sliced strawberries. Eggless. Best eaten the day it arrives.",
      attributes: { servings: 16, flavour: "strawberry", eggless: true, tiers: 1 },
      tags: ["fruit", "eggless", "classic"],
      availableDates: DELIVERY,
    },
  ],
};
